
## Built-in modules: ##
from typing import Annotated
from uuid import UUID

## Third-party modules: ##
from pydantic import BaseModel, Field


class AsymmetricKeysPair(BaseModel):
    """Schema of representation a pair of asymmetric keys.""" 
    keys_id: Annotated[UUID, Field(
        default=...,
        alias="keys_id",
        title="Keys id.",
        description="Keys id. Generated by uuid4.",
    )]
    public_key: Annotated[bytes, Field(
        default=...,
        alias="public_key",
        title="Public key.",
        description="Public key to encode the data.",
    )]
    private_key: Annotated[bytes | None, Field(
        default=None,
        alias="private_key",
        title="Private key.",
        description="Private key to decrypt the data, that encoded by public key.",
    )]